/**
 * OSMRoad edge Worker.
 *
 * Two jobs:
 *   1. POST /api/ai/query — natural-language -> DuckDB SQL, via Workers AI.
 *   2. GET  /samples/*    — sample extracts, streamed out of R2.
 *
 * Everything else falls through to the static-asset layer, which serves the
 * Vite build from ./dist. `run_worker_first` in wrangler.jsonc limits worker
 * invocation to the two prefixes above, so a page load never pays for compute.
 */

import { buildNl2SqlPrompt, cleanSql, LOCAL_FALLBACK_SQL, SCHEMA_CONTEXT } from "./nl2sql"

// `Env` (ASSETS, AI, SAMPLES, AI_MODEL, …) comes from worker-configuration.d.ts,
// generated by `npm run cf-typegen`. It is never hand-written here so it cannot
// drift from wrangler.jsonc.
type WorkerEnv = Env

/** Longest prompt we will forward to a model. */
const MAX_PROMPT_CHARS = 1000

const AI_TIMEOUT_MS = 20_000

/**
 * Best-effort per-isolate rate limit.
 *
 * Workers isolates are ephemeral and per-colo, so this is a courtesy brake on
 * accidental loops rather than a real quota — it is deliberately not presented
 * as one. Real abuse control belongs in a Cloudflare Rate Limiting rule.
 */
const RATE_LIMIT_WINDOW_MS = 60_000
const RATE_LIMIT_MAX = 12
const rateLimitBuckets = new Map<string, number[]>()

function checkRateLimit(clientId: string): { allowed: true } | { allowed: false; retryAfter: number } {
	const now = Date.now()
	const cutoff = now - RATE_LIMIT_WINDOW_MS

	const recent = (rateLimitBuckets.get(clientId) ?? []).filter((ts) => ts > cutoff)
	if (recent.length >= RATE_LIMIT_MAX) {
		const oldest = recent[0] ?? now
		return { allowed: false, retryAfter: Math.ceil((RATE_LIMIT_WINDOW_MS - (now - oldest)) / 1000) }
	}

	recent.push(now)
	rateLimitBuckets.set(clientId, recent)

	// Keep the map from growing without bound inside a long-lived isolate.
	if (rateLimitBuckets.size > 5000) {
		for (const [key, stamps] of rateLimitBuckets) {
			if (stamps.every((ts) => ts <= cutoff)) rateLimitBuckets.delete(key)
		}
	}

	return { allowed: true }
}

function json(body: unknown, init: ResponseInit = {}): Response {
	return new Response(JSON.stringify(body), {
		...init,
		headers: { "Content-Type": "application/json; charset=utf-8", ...(init.headers ?? {}) },
	})
}

/**
 * Extract the generated SQL from a Workers AI text response.
 *
 * Chat models answer with `{ response: string }`; some return an OpenAI-shaped
 * `{ choices: [{ message: { content } }] }`. Both shapes show up across the
 * catalogue, so both are handled rather than pinned to one model.
 */
function extractText(result: unknown): string {
	if (typeof result === "string") return result
	if (!result || typeof result !== "object") return ""

	const record = result as Record<string, unknown>

	if (typeof record.response === "string") return record.response

	const choices = record.choices
	if (Array.isArray(choices) && choices.length > 0) {
		const first = choices[0] as Record<string, unknown> | undefined
		const message = first?.message as Record<string, unknown> | undefined
		if (typeof message?.content === "string") return message.content
		if (typeof first?.text === "string") return first.text
	}

	return ""
}

async function runModel(env: WorkerEnv, model: string, prompt: string): Promise<string> {
	const result = await env.AI.run(model as keyof AiModels, {
		messages: [
			{ role: "system", content: SCHEMA_CONTEXT },
			{ role: "user", content: prompt },
		],
		temperature: 0.1,
		max_tokens: 512,
	})
	return extractText(result)
}

async function handleAiQuery(request: Request, env: WorkerEnv): Promise<Response> {
	if (request.method !== "POST") {
		return json({ error: "Method not allowed", success: false }, { status: 405, headers: { Allow: "POST" } })
	}

	const clientId = request.headers.get("CF-Connecting-IP") ?? "anonymous"
	const limit = checkRateLimit(clientId)
	if (!limit.allowed) {
		return json(
			{ error: `Rate limit exceeded. Please wait ${limit.retryAfter} seconds.`, success: false },
			{ status: 429, headers: { "Retry-After": String(limit.retryAfter) } },
		)
	}

	let prompt: string
	try {
		const body = (await request.json()) as { prompt?: unknown }
		prompt = typeof body.prompt === "string" ? body.prompt.trim() : ""
	} catch {
		return json({ error: "Invalid JSON body", success: false }, { status: 400 })
	}

	if (prompt.length === 0) {
		return json({ error: "Prompt is required", success: false }, { status: 400 })
	}
	if (prompt.length > MAX_PROMPT_CHARS) {
		return json({ error: `Prompt too long (max ${MAX_PROMPT_CHARS} chars)`, success: false }, { status: 400 })
	}

	const fullPrompt = buildNl2SqlPrompt(prompt)

	// Race the model against a timeout, then fall back to a smaller model once.
	// The client keeps its own offline parser, so a hard failure here is
	// recoverable — we return 503 rather than a wrong query.
	const attempt = async (model: string): Promise<string> => {
		const controller = new AbortController()
		const timer = setTimeout(() => controller.abort(), AI_TIMEOUT_MS)
		try {
			return await runModel(env, model, fullPrompt)
		} finally {
			clearTimeout(timer)
		}
	}

	let text = ""
	try {
		text = await attempt(env.AI_MODEL)
	} catch (error) {
		console.error("Primary model failed", { model: env.AI_MODEL, error: String(error) })
	}

	if (text.trim().length === 0 && env.AI_FALLBACK_MODEL) {
		try {
			text = await attempt(env.AI_FALLBACK_MODEL)
		} catch (error) {
			console.error("Fallback model failed", { model: env.AI_FALLBACK_MODEL, error: String(error) })
		}
	}

	const sql = cleanSql(text)
	if (sql.length === 0) {
		const fallback = LOCAL_FALLBACK_SQL(prompt)
		if (fallback) return json({ sql: fallback, success: true, source: "heuristic" })
		return json({ error: "Model returned no SQL", success: false }, { status: 503 })
	}

	return json({ sql, success: true, source: "workers-ai", model: env.AI_MODEL })
}

/**
 * Stream a sample extract out of R2.
 *
 * These live in R2 rather than in the asset bundle because Cloudflare caps a
 * single static asset at 25 MiB and the Taipei extract alone is 75 MB. R2 also
 * keeps the deploy small: the built Worker ships ~2 MB instead of ~110 MB.
 */
async function handleSample(request: Request, env: WorkerEnv, url: URL): Promise<Response> {
	if (request.method !== "GET" && request.method !== "HEAD") {
		return new Response("Method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } })
	}

	// `/samples/foo.osm.pbf` -> `foo.osm.pbf`. Reject traversal and nesting.
	const key = decodeURIComponent(url.pathname.slice("/samples/".length))
	if (key.length === 0 || key.includes("..") || key.includes("/")) {
		return new Response("Not found", { status: 404 })
	}

	// R2 honours a Range request header directly and hands back the slice it
	// actually served in `object.range`.
	const rangeHeader = request.headers.get("range")
	const object = await env.STORAGE.get(key, rangeHeader ? { range: request.headers } : undefined)
	if (!object) {
		return new Response("Sample not found", { status: 404 })
	}

	const headers = new Headers()
	object.writeHttpMetadata(headers)
	headers.set("ETag", object.httpEtag)
	headers.set("Cache-Control", "public, max-age=31536000, immutable")
	headers.set("Accept-Ranges", "bytes")
	// Keeps these fetchable from a cross-origin-isolated page even if a future
	// sample ends up served from another origin.
	headers.set("Cross-Origin-Resource-Policy", "cross-origin")

	const range = object.range
	const isPartial =
		rangeHeader !== null && range !== undefined && "offset" in range && typeof range.offset === "number"

	if (isPartial && range !== undefined && "offset" in range && typeof range.offset === "number") {
		const start = range.offset
		const length = range.length ?? object.size - start
		headers.set("Content-Range", `bytes ${start}-${start + length - 1}/${object.size}`)
		return new Response(request.method === "HEAD" ? null : object.body, { status: 206, headers })
	}

	headers.set("Content-Length", String(object.size))
	return new Response(request.method === "HEAD" ? null : object.body, { status: 200, headers })
}

/**
 * Serve DuckDB-wasm's `eh` module.
 *
 * This deliberately does NOT go through the static-asset layer: the raw module
 * is 32.7 MiB and Cloudflare rejects any single static asset over 25 MiB.
 *
 * Nor is it pre-compressed. Two attempts at that both produced a body the
 * browser could not use — `_headers` + a gzipped asset came back as gzip inside
 * gzip, and a gzipped R2 object served with a manual `Content-Encoding: gzip`
 * was re-compressed by the edge into the same double-encoded shape. So the raw
 * module is stored and returned as-is, with no Content-Encoding set, and
 * Cloudflare's own content negotiation handles transfer compression and labels
 * it correctly. Verified with curl: a gzip-accepting request decodes in exactly
 * one step to a module starting with the wasm magic.
 */
async function handleDuckdbWasm(request: Request, env: WorkerEnv): Promise<Response> {
	if (request.method !== "GET" && request.method !== "HEAD") {
		return new Response("Method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } })
	}

	const object = await env.STORAGE.get("duckdb/duckdb-eh.wasm")
	if (!object) {
		console.error("DuckDB wasm missing from R2")
		return new Response(
			'DuckDB wasm not uploaded. Run: npm run assets:upload\n(missing r2 object "duckdb/duckdb-eh.wasm")',
			{ status: 503, headers: { "Content-Type": "text/plain; charset=utf-8" } },
		)
	}

	const headers = new Headers()
	headers.set("Content-Type", "application/wasm")
	headers.set("Cache-Control", "public, max-age=31536000, immutable")
	headers.set("ETag", object.httpEtag)
	headers.set("Content-Length", String(object.size))

	return new Response(request.method === "HEAD" ? null : object.body, { status: 200, headers })
}

export default {
	async fetch(request: Request, env: WorkerEnv): Promise<Response> {
		const url = new URL(request.url)

		try {
			if (url.pathname === "/api/ai/query") {
				return await handleAiQuery(request, env)
			}
			if (url.pathname === "/api/health") {
				return json({ ok: true, model: env.AI_MODEL })
			}
			if (url.pathname.startsWith("/samples/")) {
				return await handleSample(request, env, url)
			}
			if (url.pathname === "/duckdb/duckdb-eh.wasm") {
				return await handleDuckdbWasm(request, env)
			}
		} catch (error) {
			console.error("Worker error", { path: url.pathname, error: String(error) })
			return json({ error: "Internal server error", success: false }, { status: 500 })
		}

		// `run_worker_first` only routes /api/* and /samples/* here, so this is
		// reached only by an unmatched API path; defer to the asset layer so the
		// SPA fallback stays consistent.
		return env.ASSETS.fetch(request)
	},
} satisfies ExportedHandler<WorkerEnv>
