/**
 * OSMRoad edge Worker.
 *
 * Three jobs:
 *   1. POST /api/ai/query — natural-language -> DuckDB SQL, via SumoPod or Workers AI.
 *   2. POST /api/overpass — Overpass proxy for the draw-an-area flow.
 *   3. GET  /samples/*    — sample extracts, streamed out of R2.
 *   4. GET  /duckdb/*     — the DuckDB wasm module, streamed out of R2.
 *
 * Everything else falls through to the static-asset layer, which serves the
 * Vite build from ./dist. `run_worker_first` in wrangler.jsonc limits worker
 * invocation to those prefixes, so a page load never pays for compute.
 */

import { buildNl2SqlPrompt, cleanSql, LOCAL_FALLBACK_SQL, SCHEMA_CONTEXT } from "./nl2sql"
import { bboxAreaKm2, buildRoadsQuery, fetchFromOverpass, MAX_AREA_KM2, parseBbox } from "./overpass"

// `Env` (ASSETS, AI, STORAGE, AI_MODEL, …) comes from worker-configuration.d.ts,
// generated by `npm run cf-typegen`. It is never hand-written here so it cannot
// drift from wrangler.jsonc.
type WorkerEnv = Env

/** Edge cache holding recent Overpass responses. */
const OVERPASS_CACHE = "osmroad-overpass"

/** Longest prompt we will forward to a model. */
const MAX_PROMPT_CHARS = 1000

const AI_TIMEOUT_MS = 20_000

/** Which backend answered, reported back to the client in `source`. */
type AiSource = "sumopod" | "workers-ai"

interface ChatMessage {
	role: "system" | "user"
	content: string
}

/**
 * Best-effort per-isolate rate limit.
 *
 * Workers isolates are ephemeral and per-colo, so this is a courtesy brake on
 * accidental loops rather than a real quota — it is deliberately not presented
 * as one. With a paid provider key behind this endpoint the real control is a
 * Cloudflare Rate Limiting rule on /api/ai/query; see README.
 */
const RATE_LIMIT_WINDOW_MS = 60_000
const RATE_LIMIT_MAX = 12
const rateLimitBuckets = new Map<string, number[]>()

function checkRateLimit(clientId: string): { allowed: true } | { allowed: false; retryAfter: number } {
	const now = Date.now()
	const cutoff = now - RATE_LIMIT_WINDOW_MS

	const recent = (rateLimitBuckets.get(clientId) ?? []).filter((ts) => ts > cutoff)
	if (recent.length >= RATE_LIMIT_MAX) {
		const oldest = recent[0] ?? now
		return { allowed: false, retryAfter: Math.ceil((RATE_LIMIT_WINDOW_MS - (now - oldest)) / 1000) }
	}

	recent.push(now)
	rateLimitBuckets.set(clientId, recent)

	// Keep the map from growing without bound inside a long-lived isolate.
	if (rateLimitBuckets.size > 5000) {
		for (const [key, stamps] of rateLimitBuckets) {
			if (stamps.every((ts) => ts <= cutoff)) rateLimitBuckets.delete(key)
		}
	}

	return { allowed: true }
}

/** Cache keys must be stable and short; the query itself is far too long. */
async function sha256Hex(value: string): Promise<string> {
	const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value))
	return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("")
}

function json(body: unknown, init: ResponseInit = {}): Response {
	return new Response(JSON.stringify(body), {
		...init,
		headers: { "Content-Type": "application/json; charset=utf-8", ...(init.headers ?? {}) },
	})
}

/**
 * Extract the generated SQL from a Workers AI text response.
 *
 * Chat models answer with `{ response: string }`; some return an OpenAI-shaped
 * `{ choices: [{ message: { content } }] }`. Both shapes show up across the
 * catalogue, so both are handled rather than pinned to one model.
 */
function extractText(result: unknown): string {
	if (typeof result === "string") return result
	if (!result || typeof result !== "object") return ""

	const record = result as Record<string, unknown>

	if (typeof record.response === "string") return record.response

	const choices = record.choices
	if (Array.isArray(choices) && choices.length > 0) {
		const first = choices[0] as Record<string, unknown> | undefined
		const message = first?.message as Record<string, unknown> | undefined
		if (typeof message?.content === "string") return message.content
		if (typeof first?.text === "string") return first.text
	}

	return ""
}

/**
 * Call an OpenAI-compatible chat completions endpoint (SumoPod).
 *
 * SumoPod exposes the standard `/v1/chat/completions` shape, so this is a plain
 * fetch rather than the OpenAI SDK — the SDK would add bundle weight to the
 * Worker for one request.
 */
async function runOpenAiCompatible(
	env: WorkerEnv,
	messages: ChatMessage[],
	signal: AbortSignal,
): Promise<string> {
	const baseUrl = env.AI_BASE_URL.replace(/\/+$/, "")
	const response = await fetch(`${baseUrl}/chat/completions`, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			Authorization: `Bearer ${env.AI_API_KEY}`,
		},
		body: JSON.stringify({
			model: env.AI_MODEL,
			messages,
			temperature: 0.1,
			max_tokens: 512,
			stream: false,
		}),
		signal,
	})

	if (!response.ok) {
		// Read the body for diagnostics, but never echo it to the client: a
		// provider error can quote the request, and the request carried the key.
		const detail = await response.text().catch(() => "")
		throw new Error(`SumoPod HTTP ${response.status}: ${detail.slice(0, 300)}`)
	}

	return extractText(await response.json())
}

/** Call the Workers AI binding, which is always present. */
async function runWorkersAi(env: WorkerEnv, messages: ChatMessage[]): Promise<string> {
	const result = await env.AI.run(env.AI_FALLBACK_MODEL as keyof AiModels, {
		messages,
		temperature: 0.1,
		max_tokens: 512,
	})
	return extractText(result)
}

/**
 * Reject requests that did not come from the app itself.
 *
 * This is a drive-by-abuse brake, NOT a security boundary: `Origin` is trivial
 * to forge from a non-browser client. It only stops a random web page from
 * spending the provider budget. The real controls are the rate limit and a
 * Cloudflare Rate Limiting rule on this path.
 *
 * An empty/unset list disables the check so the endpoint keeps working if the
 * deployment moves to a new hostname before the list is updated.
 */
function originAllowed(request: Request, env: WorkerEnv): boolean {
	const allowed = (env.ALLOWED_ORIGINS ?? "")
		.split(",")
		.map((value) => value.trim())
		.filter((value) => value.length > 0)

	if (allowed.length === 0) return true

	const origin = request.headers.get("Origin")
	if (!origin) return false
	if (allowed.includes(origin)) return true

	// Same-origin requests from a hostname parked behind a proxy may report a
	// Referer instead. Accept it only if its origin is on the list.
	const referer = request.headers.get("Referer")
	if (!referer) return false
	try {
		return allowed.includes(new URL(referer).origin)
	} catch {
		return false
	}
}

async function handleAiQuery(request: Request, env: WorkerEnv): Promise<Response> {
	if (request.method !== "POST") {
		return json({ error: "Method not allowed", success: false }, { status: 405, headers: { Allow: "POST" } })
	}

	if (!originAllowed(request, env)) {
		return json(
			{ error: "Origin not allowed. Set ALLOWED_ORIGINS on the Worker.", success: false },
			{ status: 403 },
		)
	}

	const clientId = request.headers.get("CF-Connecting-IP") ?? "anonymous"
	const limit = checkRateLimit(clientId)
	if (!limit.allowed) {
		return json(
			{ error: `Rate limit exceeded. Please wait ${limit.retryAfter} seconds.`, success: false },
			{ status: 429, headers: { "Retry-After": String(limit.retryAfter) } },
		)
	}

	let prompt: string
	try {
		const body = (await request.json()) as { prompt?: unknown }
		prompt = typeof body.prompt === "string" ? body.prompt.trim() : ""
	} catch {
		return json({ error: "Invalid JSON body", success: false }, { status: 400 })
	}

	if (prompt.length === 0) {
		return json({ error: "Prompt is required", success: false }, { status: 400 })
	}
	if (prompt.length > MAX_PROMPT_CHARS) {
		return json({ error: `Prompt too long (max ${MAX_PROMPT_CHARS} chars)`, success: false }, { status: 400 })
	}

	const messages: ChatMessage[] = [
		{ role: "system", content: SCHEMA_CONTEXT },
		{ role: "user", content: buildNl2SqlPrompt(prompt) },
	]

	// Preset is the OpenAI-compatible provider when a key is configured, and the
	// Workers AI binding otherwise — so the feature works before the secret is
	// set, and a provider outage degrades to the other backend rather than to an
	// error. The client keeps its own offline parser behind both.
	const sumopodConfigured = (env.AI_API_KEY ?? "").trim().length > 0
	const order: AiSource[] = sumopodConfigured ? ["sumopod", "workers-ai"] : ["workers-ai"]

	let text = ""
	let source: AiSource | null = null
	/** The model that actually produced the answer, for honest reporting. */
	let answeringModel: string = env.AI_MODEL

	for (const candidate of order) {
		const controller = new AbortController()
		const timer = setTimeout(() => controller.abort(), AI_TIMEOUT_MS)
		try {
			const produced =
				candidate === "sumopod"
					? await runOpenAiCompatible(env, messages, controller.signal)
					: await runWorkersAi(env, messages)
			if (produced.trim().length > 0) {
				text = produced
				source = candidate
				answeringModel = candidate === "sumopod" ? env.AI_MODEL : env.AI_FALLBACK_MODEL
				break
			}
			console.error("AI provider returned empty output", {
				provider: candidate,
				model: candidate === "sumopod" ? env.AI_MODEL : env.AI_FALLBACK_MODEL,
			})
		} catch (error) {
			console.error("AI provider failed", { provider: candidate, error: String(error) })
		} finally {
			clearTimeout(timer)
		}
	}

	const sql = cleanSql(text)
	if (sql.length === 0) {
		const fallback = LOCAL_FALLBACK_SQL(prompt)
		if (fallback) return json({ sql: fallback, success: true, source: "heuristic" })
		return json({ error: "No AI provider returned usable SQL", success: false }, { status: 503 })
	}

	return json({ sql, success: true, source, model: answeringModel })
}

/**
 * Proxy the "draw an area, fetch roads from OSM" flow.
 *
 * The client sends a bounding box, never a query: the query is built here so
 * this endpoint cannot be driven as a general-purpose Overpass gateway.
 */
async function handleOverpass(request: Request, ctx: ExecutionContext): Promise<Response> {
	if (request.method !== "POST") {
		return json({ error: "Method not allowed", success: false }, { status: 405, headers: { Allow: "POST" } })
	}

	let bbox
	try {
		const body = (await request.json()) as { bbox?: unknown }
		bbox = parseBbox(body.bbox)
	} catch {
		return json({ error: "Invalid JSON body", success: false }, { status: 400 })
	}

	if (!bbox) {
		return json(
			{ error: "Expected { bbox: [minLon, minLat, maxLon, maxLat] }", success: false },
			{ status: 400 },
		)
	}

	const areaKm2 = bboxAreaKm2(bbox)
	if (areaKm2 > MAX_AREA_KM2) {
		return json(
			{
				error: `Area too large (${areaKm2.toFixed(1)} km²). Maximum is ${MAX_AREA_KM2} km².`,
				success: false,
			},
			{ status: 413 },
		)
	}

	const query = buildRoadsQuery(bbox)

	// OSM data changes slowly and a user often redraws the same box, so a short
	// edge cache both speeds up the second attempt and keeps load off mirrors
	// that are run on donations.
	// A named cache rather than `caches.default`: tsconfig pulls in the DOM lib,
	// whose CacheStorage type has no `default` member, and this is typed
	// correctly under both.
	const cache = await caches.open(OVERPASS_CACHE)
	const cacheKey = new Request(
		`https://osmroad.internal/overpass/${await sha256Hex(query)}`,
		{ method: "GET" },
	)
	const cached = await cache.match(cacheKey)
	if (cached) {
		const xml = await cached.text()
		return new Response(xml, {
			status: 200,
			headers: {
				"Content-Type": "application/osm+xml; charset=utf-8",
				"X-OSMRoad-Cache": "hit",
				"Cache-Control": "public, max-age=1800",
			},
		})
	}

	const result = await fetchFromOverpass(query)
	if (!("xml" in result)) {
		// Report every mirror's failure: "it did not work" is not actionable,
		// "overpass-api.de said 406, the other two timed out" is.
		const detail = result.attempts
			.map((a) => `${new URL(a.endpoint).host}: ${a.error ?? "unknown"}${a.status ? ` (${a.status})` : ""}`)
			.join("; ")
		console.error("All Overpass mirrors failed", { detail })
		return json(
			{
				error: `Could not reach any Overpass instance. ${detail}`,
				success: false,
			},
			{ status: 502 },
		)
	}

	const response = new Response(result.xml, {
		status: 200,
		headers: {
			"Content-Type": "application/osm+xml; charset=utf-8",
			"X-OSMRoad-Cache": "miss",
			"X-OSMRoad-Mirror": new URL(result.endpoint).host,
			"Cache-Control": "public, max-age=1800",
		},
	})
	ctx.waitUntil(cache.put(cacheKey, response.clone()))
	return response
}

/**
 * Stream a sample extract out of R2.
 *
 * These live in R2 rather than in the asset bundle because Cloudflare caps a
 * single static asset at 25 MiB and the Taipei extract alone is 75 MB. R2 also
 * keeps the deploy small: the built Worker ships ~2 MB instead of ~110 MB.
 */
async function handleSample(request: Request, env: WorkerEnv, url: URL): Promise<Response> {
	if (request.method !== "GET" && request.method !== "HEAD") {
		return new Response("Method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } })
	}

	// `/samples/foo.osm.pbf` -> `foo.osm.pbf`. Reject traversal and nesting.
	const key = decodeURIComponent(url.pathname.slice("/samples/".length))
	if (key.length === 0 || key.includes("..") || key.includes("/")) {
		return new Response("Not found", { status: 404 })
	}

	// R2 honours a Range request header directly and hands back the slice it
	// actually served in `object.range`.
	const rangeHeader = request.headers.get("range")
	const object = await env.STORAGE.get(key, rangeHeader ? { range: request.headers } : undefined)
	if (!object) {
		return new Response("Sample not found", { status: 404 })
	}

	const headers = new Headers()
	object.writeHttpMetadata(headers)
	headers.set("ETag", object.httpEtag)
	headers.set("Cache-Control", "public, max-age=31536000, immutable")
	headers.set("Accept-Ranges", "bytes")
	// Keeps these fetchable from a cross-origin-isolated page even if a future
	// sample ends up served from another origin.
	headers.set("Cross-Origin-Resource-Policy", "cross-origin")

	const range = object.range
	const isPartial =
		rangeHeader !== null && range !== undefined && "offset" in range && typeof range.offset === "number"

	if (isPartial && range !== undefined && "offset" in range && typeof range.offset === "number") {
		const start = range.offset
		const length = range.length ?? object.size - start
		headers.set("Content-Range", `bytes ${start}-${start + length - 1}/${object.size}`)
		return new Response(request.method === "HEAD" ? null : object.body, { status: 206, headers })
	}

	headers.set("Content-Length", String(object.size))
	return new Response(request.method === "HEAD" ? null : object.body, { status: 200, headers })
}

/**
 * Serve DuckDB-wasm's `eh` module.
 *
 * This deliberately does NOT go through the static-asset layer: the raw module
 * is 32.7 MiB and Cloudflare rejects any single static asset over 25 MiB.
 *
 * Nor is it pre-compressed. Two attempts at that both produced a body the
 * browser could not use — `_headers` + a gzipped asset came back as gzip inside
 * gzip, and a gzipped R2 object served with a manual `Content-Encoding: gzip`
 * was re-compressed by the edge into the same double-encoded shape. So the raw
 * module is stored and returned as-is, with no Content-Encoding set, and
 * Cloudflare's own content negotiation handles transfer compression and labels
 * it correctly. Verified with curl: a gzip-accepting request decodes in exactly
 * one step to a module starting with the wasm magic.
 */
async function handleDuckdbWasm(request: Request, env: WorkerEnv): Promise<Response> {
	if (request.method !== "GET" && request.method !== "HEAD") {
		return new Response("Method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } })
	}

	const object = await env.STORAGE.get("duckdb/duckdb-eh.wasm")
	if (!object) {
		console.error("DuckDB wasm missing from R2")
		return new Response(
			'DuckDB wasm not uploaded. Run: npm run assets:upload\n(missing r2 object "duckdb/duckdb-eh.wasm")',
			{ status: 503, headers: { "Content-Type": "text/plain; charset=utf-8" } },
		)
	}

	const headers = new Headers()
	headers.set("Content-Type", "application/wasm")
	headers.set("Cache-Control", "public, max-age=31536000, immutable")
	headers.set("ETag", object.httpEtag)
	headers.set("Content-Length", String(object.size))

	return new Response(request.method === "HEAD" ? null : object.body, { status: 200, headers })
}

export default {
	async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url)

		try {
			if (url.pathname === "/api/ai/query") {
				return await handleAiQuery(request, env)
			}
			if (url.pathname === "/api/overpass") {
				return await handleOverpass(request, ctx)
			}
			if (url.pathname === "/api/health") {
				return json({ ok: true, model: env.AI_MODEL })
			}
			if (url.pathname.startsWith("/samples/")) {
				return await handleSample(request, env, url)
			}
			if (url.pathname === "/duckdb/duckdb-eh.wasm") {
				return await handleDuckdbWasm(request, env)
			}
		} catch (error) {
			console.error("Worker error", { path: url.pathname, error: String(error) })
			return json({ error: "Internal server error", success: false }, { status: 500 })
		}

		// `run_worker_first` only routes /api/* and /samples/* here, so this is
		// reached only by an unmatched API path; defer to the asset layer so the
		// SPA fallback stays consistent.
		return env.ASSETS.fetch(request)
	},
} satisfies ExportedHandler<WorkerEnv>
